[tool.black]
line-length = 100
target-version = ["py311"]
color = true
preview = true

[tool.docformatter]
make-summary-multi-line = true
pre-summary-newline = true
recursive = true
wrap-summaries = 80
wrap-descriptions = 80

[tool.mypy]
explicit_package_bases = true
strict = true
pretty = true

[tool.ruff]
exclude = []
line-length = 100
select = ["E", "I", "F"]